services:
  - type: web
    name: my-dev-environment
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: ROOT_PASSWORD
        value: secret
      - key: USER_PASSWORD
        value: secret
      - key: USER_NAME
        value: user
